version: '3.7'

services:
  app:
    build:
      context: guestlist 
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

